Traceback (most recent call last):
  File "start.py", line 118, in seleccand
IndexError: list index out of range
Traceback (most recent call last):
  File "start.py", line 118, in seleccand
IndexError: list index out of range
Traceback (most recent call last):
  File "start.py", line 118, in seleccand
IndexError: list index out of range
Traceback (most recent call last):
  File "start.py", line 118, in seleccand
IndexError: list index out of range
Traceback (most recent call last):
  File "start.py", line 118, in seleccand
IndexError: list index out of range
